### PR TITLE
Changes to files for easier maintenance in version control

### PR DESCRIPTION
**Pull request by sagatowski**
Did a few things:
- Hidden unused configurations
- Removed LineIDs from all files (this should be documented to be disabled by default, see https://github.com/tcunit/TcUnit/blob/master/CONTRIBUTING.md for TcUnit)
- Removed "Write product version in files" as this is not necessary (a setting that is saved in the project, so not necessary to update your development environment)

This will make maintaining this project easier, as you will have less unnecessary changes to files when doing changes to the project.

### CODE REVIEW

**Review by fisothemes — APPROVED** [review]
I've reviewed your changes and I think they look great. I'm approving this pull request. I'll merge it into the main branch in a few minutes.

Thanks again for your contribution and for the tips.

**Comment by Roald87** [comment]
In order to prevent these LineIDs from creeping back in, you can use a `.pre-commit.yaml`. [Here](https://github.com/rruiter87/tctemplate) is a template that I made for twincat, based on the pre-commit from [these people](https://github.com/pcdshub/pre-commit-hooks). If you do not know what a pre-commit is, I explain that [here](https://cookncode.com/twincat/2022/04/14/pre-commit.html).

**Comment by sagatowski** [comment]
This is a great suggestion @Roald87! I generally create a MD-file explaining what settings every developer should use, but this is a much more automated way.

**Comment by fisothemes** [comment]
@Roald87  Amazing, will read-up on it and thanks for the suggestion and for writing an article on how to do it.

**Pull request merged**
